# Generated by Django 2.2 on 2020-12-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de Acceso', max_length=191)),
                ('slug', models.CharField(help_text='Ruta Amigable Acceso', max_length=191)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de Acceso', max_length=191, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'accesos',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del Menú', max_length=191)),
                ('enlace', models.CharField(help_text='Ruta Menú', max_length=191)),
                ('icono', models.CharField(blank=True, help_text='Icono del Menú', max_length=191, null=True)),
                ('padre', models.IntegerField(default=0, help_text='Padre del Menú')),
                ('orden', models.SmallIntegerField(blank=True, help_text='Orden de menú', null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de Acceso', max_length=191)),
                ('slug', models.CharField(help_text='Ruta Amigable Acceso', max_length=191)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de Acceso', max_length=191, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción Sexo', max_length=191)),
            ],
            options={
                'verbose_name_plural': 'sexos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(blank=True, help_text='Código Tipo Documento', max_length=2, null=True)),
                ('nombre_corto', models.CharField(blank=True, help_text='Descripción Corta', max_length=191, null=True)),
                ('nombre_largo', models.CharField(blank=True, help_text='Descripción Larga', max_length=191, null=True)),
                ('longitud', models.PositiveSmallIntegerField(help_text='Longitud Documento')),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
            ],
            options={
                'verbose_name_plural': 'tipo_documentos',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre de Rol', max_length=191, null=True)),
                ('slug', models.CharField(blank=True, help_text='Ruta Amigable Rol', max_length=191, null=True)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de Rol', max_length=191, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
                ('acceso', models.ForeignKey(blank=True, help_text='Persona Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.Acceso')),
                ('menus', models.ManyToManyField(to='cuenta.Menu')),
                ('permisos', models.ManyToManyField(to='cuenta.Permiso')),
            ],
            options={
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('numero_documento', models.CharField(help_text='Número Documento', max_length=15)),
                ('nombres', models.CharField(help_text='Nombres', max_length=191)),
                ('apellidos', models.CharField(help_text='Apellidos', max_length=191)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección', max_length=191, null=True)),
                ('sexo', models.ForeignKey(blank=True, help_text='Sexo Persona', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.Sexo')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.TipoDocumento')),
            ],
            options={
                'verbose_name_plural': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Nombre Usuario', max_length=191, unique=True)),
                ('email', models.EmailField(blank=True, help_text='Correo Electrónico', max_length=191, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de Perfil', max_length=191, null=True, upload_to='media/imagen/')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificada', models.DateTimeField(auto_now=True)),
                ('fecha_eliminada', models.DateTimeField(blank=True, help_text='Fecha Eliminada', null=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Persona Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Empresa')),
                ('persona', models.OneToOneField(blank=True, help_text='Persona Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.Persona')),
                ('roles', models.ManyToManyField(to='cuenta.Role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
