# Generated by Django 2.2 on 2020-12-11 03:29

from django.db import migrations,models

class AsignarRolesUsuario:
    @classmethod
    def cargar_datos(cls,apps, schema_editor):
        db_alias =schema_editor.connection.alias

        Role = apps.get_model('cuenta','Role')
        Usuario = apps.get_model('cuenta','Usuario')

        role_su = Role.objects.get(slug='super-usuario')
        usuario_man = Usuario.objects.get(nombre='admin')
        usuario_man.roles.add(role_su)
        print(f'\nRol '+str(role_su.nombre)+' asignado a '+str(usuario_man.nombre))


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_auto_20201210_2021'),
    ]

    operations = [
        migrations.RunPython(AsignarRolesUsuario.cargar_datos)
    ]
