# Generated by Django 2.2 on 2020-12-12 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción Producto', max_length=191)),
                ('imagen', models.BinaryField(blank=True, editable=True, help_text='Imagen Producto', null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Empresa')),
            ],
            options={
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción Tipo Producto', max_length=191)),
            ],
            options={
                'verbose_name_plural': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Descripción Tipo Producto', max_length=191)),
            ],
            options={
                'verbose_name_plural': 'tipo_productos',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parte', models.CharField(blank=True, help_text='Descripción Número parte', max_length=50, null=True)),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Código de Proveedor', max_length=50, null=True)),
                ('codigo_interno', models.CharField(blank=True, help_text='Código Interno', max_length=50, null=True)),
                ('codigo_sunat', models.CharField(blank=True, help_text='Código Producto Sunat', max_length=50, null=True)),
                ('nombre', models.CharField(help_text='Descripción de Producto', max_length=191, unique=True)),
                ('detalle', models.TextField(blank=True, help_text='Detalle de Producto', max_length=255, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen Producto', null=True, upload_to='productos/images/')),
                ('afecto_igv', models.BooleanField(blank=True, help_text='IGV Afecto', null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Categoria')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Empresa')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Marca')),
                ('tipo_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.TipoProducto')),
            ],
            options={
                'verbose_name_plural': 'productos',
            },
        ),
    ]
