# Generated by Django 2.2 on 2020-12-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'verbose_name_plural': 'tipo_productos'},
        ),
    ]
