# Generated by Django 2.2 on 2020-12-11 01:21
from django.db import models,migrations

class DatosMigracion:
    @classmethod
    def cargar_datos(cls,apps,schema_editor):
        db_alias =schema_editor.connection.alias

        TipoProducto = apps.get_model('prod','TipoProducto')

        cls.tipo_materia_prima, created = TipoProducto.objects.get_or_create(nombre='Materia Prima y Auxiliares')
        print(f'\nTipo Producto creado: '+str(cls.tipo_materia_prima.nombre))

        cls.tipo_preparado, created = TipoProducto.objects.get_or_create(nombre='Producto Preparado')
        print(f'\nTipo Producto creado: '+str(cls.tipo_preparado.nombre))

        cls.tipo_terminado, created = TipoProducto.objects.get_or_create(nombre='Producto Terminado')
        print(f'\nTipo Producto creado: '+str(cls.tipo_terminado.nombre))

class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(DatosMigracion.cargar_datos)
    ]
