# Generated by Django 2.2 on 2020-12-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_auto_20201210_2012'),
    ]

    operations = [
    ]
