# Generated by Django 2.2 on 2020-12-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_ingrediente_productopreparado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopreparado',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_preparados', to='prod.Producto'),
        ),
    ]
