# Generated by Django 2.2 on 2020-12-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0005_auto_20201223_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productopreparado',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Producto'),
        ),
    ]
