# Generated by Django 2.2 on 2021-01-11 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prod', '0006_auto_20201223_0734'),
        ('emp', '0007_auto_20210110_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteVenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_comprobante', models.CharField(help_text='Serie Comprobante', max_length=4)),
                ('numero_comprobante', models.PositiveIntegerField(help_text='Número Comprobante')),
                ('fecha', models.DateTimeField(help_text='Fecha Comprobante')),
                ('sub_total', models.DecimalField(decimal_places=2, help_text='Sub Total', max_digits=18)),
                ('igv', models.DecimalField(decimal_places=2, default=0.0, help_text='Sub Total', max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento', max_digits=18)),
                ('operaciones_gravadas', models.DecimalField(decimal_places=2, default=0.0, help_text='Operaciones Gravadas', max_digits=18)),
                ('operaciones_exoneradas', models.DecimalField(decimal_places=2, default=0.0, help_text='operaciones Exoneradas', max_digits=18)),
                ('operaciones_inafecta', models.DecimalField(decimal_places=2, default=0.0, help_text='Operaciones Inafectas', max_digits=18)),
                ('operaciones_gratuitas', models.DecimalField(decimal_places=2, default=0.0, help_text='Operaciones Gratuitas', max_digits=18)),
                ('impuesto_bolsa', models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto Bolsa', max_digits=18)),
                ('percepciones', models.DecimalField(decimal_places=2, default=0.0, help_text='percepciones', max_digits=18)),
                ('retenciones', models.DecimalField(decimal_places=2, default=0.0, help_text='Retenciones', max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, help_text='Total Venta', max_digits=18)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha Vencimiento')),
                ('estado_xml', models.BooleanField(blank=True, help_text='Estado XML', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoOperacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre Estado Operación', max_length=191, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código Forma de Pago', max_length=3, null=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre Forma de Pago', max_length=191, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código Forma de Pago', max_length=3, null=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre Forma de Pago', max_length=191, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código de Comprobante', max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre Tipo Comprobante', max_length=191, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código Forma de Pago', max_length=3, null=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre Forma de Pago', max_length=191, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteVentaDetalle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(help_text='Cantidad de Item')),
                ('precio_venta_final', models.DecimalField(decimal_places=2, help_text='Retenciones', max_digits=18)),
                ('importe', models.DecimalField(decimal_places=2, help_text='Operaciones Gravadas', max_digits=18)),
                ('operaciones_gravadas', models.DecimalField(decimal_places=2, default=0.0, help_text='Operaciones Gravadas', max_digits=18)),
                ('operaciones_exoneradas', models.DecimalField(decimal_places=2, default=0.0, help_text='operaciones Exoneradas', max_digits=18)),
                ('operaciones_inafecta', models.DecimalField(decimal_places=2, default=0.0, help_text='Operaciones Inafectas', max_digits=18)),
                ('operaciones_gratuitas', models.DecimalField(decimal_places=2, default=0.0, help_text='Operaciones Gratuitas', max_digits=18)),
                ('impuesto_bolsa', models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto Bolsa', max_digits=18)),
                ('percepciones', models.DecimalField(decimal_places=2, default=0.0, help_text='percepciones', max_digits=18)),
                ('retenciones', models.DecimalField(decimal_places=2, default=0.0, help_text='Retenciones', max_digits=18)),
                ('comprobante_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.ComprobanteVenta')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prod.Producto')),
                ('unidad_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.UnidadMedida')),
            ],
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='estado_operacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.EstadoOperacion'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='forma_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.FormaPago'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.Moneda'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Sucursal'),
        ),
        migrations.AddField(
            model_name='comprobanteventa',
            name='tipo_comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.TipoComprobante'),
        ),
    ]
