# Generated by Django 2.2 on 2020-12-20 21:44

from django.db import models,migrations

class VentasDatos:
    @classmethod
    def cargar_datos(cls,apps,schema_editor):
        db_alias = schema_editor.connection.alias
        
        TipoComprobante = apps.get_model('ventas','TipoComprobante')
        
        # cls.tipo_comprobante1, created = TipoComprobante.objects.get_or_create(codigo='01',nombre='')
        # print(f'\nTipo Punto de Venta creado: '+str(cls.tipo_tactil.nombre))

        # TipoPuntoVenta = apps.get_model('emp','TipoPuntoVenta')

        # cls.tipo_tactil, created = TipoPuntoVenta.objects.get_or_create(nombre='Táctil')
        # print(f'\nTipo Punto de Venta creado: '+str(cls.tipo_tactil.nombre))

        # cls.tipo_no_tactil, created = TipoPuntoVenta.objects.get_or_create(nombre='No Táctil')
        # print(f'\nTipo Punto de Venta creado: '+str(cls.tipo_no_tactil.nombre))

        # TipoAlmacen = apps.get_model('emp','TipoAlmacen')

        # cls.tipo_superficie, created = TipoAlmacen.objects.get_or_create(nombre='Almacén en Superficie')
        # print(f'\nTipo Almacén creado: '+str(cls.tipo_superficie.nombre))

        # cls.tipo_tanque, created = TipoAlmacen.objects.get_or_create(nombre='Almacén Tanque')
        # print(f'\nTipo Almacén creado: '+str(cls.tipo_tanque.nombre))

class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(ConfiguracionesDatos.cargar_datos)
    ]
