# Generated by Django 2.2 on 2021-01-21 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20210111_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlDetalle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRegistro', models.DateTimeField(help_text='Fecha Comprobante')),
                ('diaRegistro', models.IntegerField(help_text='Dia Registro Comprobante')),
                ('fechaEnvio', models.DateTimeField(help_text='Fecha Comprobante')),
                ('id_comprobante', models.BigIntegerField(help_text='Id Comprobante')),
                ('serie', models.CharField(blank=True, help_text='Código Forma de Pago', max_length=4, null=True)),
                ('numero', models.IntegerField(help_text='Dia Registro Comprobante')),
                ('estadoComprobante', models.BooleanField(default=True)),
                ('nombre_xml', models.CharField(blank=True, help_text='Nombre Forma de Pago', max_length=191, null=True)),
                ('estado_envio', models.CharField(default=0, help_text='Estado Envio', max_length=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.TipoComprobante')),
            ],
        ),
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='estado_operacion',
        ),
        migrations.RemoveField(
            model_name='comprobanteventa',
            name='estado_xml',
        ),
        migrations.AddField(
            model_name='serie',
            name='correlativo_actual',
            field=models.IntegerField(blank=True, help_text='Correlativo Actual', null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='correlativo_inicial',
            field=models.IntegerField(default=1, help_text='Correlativo Inicial'),
        ),
        migrations.DeleteModel(
            name='EstadoOperacion',
        ),
    ]
