# Generated by Django 2.2 on 2020-11-26 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=191)),
                ('direccion', models.CharField(max_length=191)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('capacidad', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'verbose_name_plural': 'Almacenes',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción Departamento', max_length=191)),
            ],
            options={
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción de Distrito', max_length=191)),
            ],
            options={
                'verbose_name_plural': 'Distritos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(help_text=' R.U.C. de Empresa', max_length=11, unique=True)),
                ('razon_social', models.CharField(help_text='Razón Social Empresa', max_length=191)),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre Comercial Empresa', max_length=191, null=True)),
                ('direccion_principal', models.CharField(help_text='Dirección Empresa', max_length=191)),
                ('pagina_web', models.CharField(blank=True, help_text='URL / Dirección Web', max_length=191, null=True)),
                ('usuario_sol', models.CharField(blank=True, help_text='Usuario Clave Sol', max_length=50, null=True)),
                ('clave_sol', models.CharField(blank=True, help_text='COntraseña Clave Sol', max_length=50, null=True)),
                ('certificado_pfx', models.BinaryField(blank=True, editable=True, help_text='Archivo Certificado PFX', null=True)),
                ('fecha_caduca_certificado', models.DateField(blank=True, help_text='Fecha Caduca Certificado', null=True)),
                ('certificado_zip', models.BinaryField(blank=True, editable=True, help_text='Archivo Certificado Zip', null=True)),
                ('clave_certificado', models.CharField(blank=True, help_text='Contraseña Certificado', max_length=50, null=True)),
                ('texto_encabezado', models.CharField(blank=True, help_text='Texto Encabezado', max_length=191, null=True)),
                ('logo', models.BinaryField(blank=True, editable=True, help_text='Logo Empresa', null=True)),
                ('imagen_pie_pagina', models.BinaryField(blank=True, editable=True, help_text='Imagen de Pié de Página', null=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='TipoAlmacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'verbose_name_plural': 'TipoAlmacenes',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Codigo Tipo Empresa', max_length=2)),
                ('nombre', models.CharField(help_text='Descripción de Tipo Empresa', max_length=191)),
                ('comentario', models.CharField(blank=True, help_text='Comentario de Tipo Empresa', max_length=191, null=True)),
            ],
            options={
                'verbose_name_plural': 'TipoEmpresas',
            },
        ),
        migrations.CreateModel(
            name='TipoPuntoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'verbose_name_plural': 'TipoPuntoVentas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('id_sunat', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre', models.CharField(blank=True, max_length=191, null=True)),
                ('impresion', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'verbose_name_plural': 'UnidadMedidas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=191)),
                ('direccion', models.CharField(max_length=191)),
                ('referencia', models.CharField(blank=True, max_length=191, null=True)),
                ('observacion', models.CharField(blank=True, max_length=191, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Empresa')),
                ('ubigeo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Distrito')),
            ],
            options={
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre_equipo', models.CharField(max_length=191)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Almacen')),
                ('tipo_punto_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.TipoPuntoVenta')),
            ],
            options={
                'verbose_name_plural': 'PuntoVentas',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Descripción de Provincia', max_length=191)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Departamento')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.TipoEmpresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Distrito'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Provincia'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Sucursal'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='tipo_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.TipoAlmacen'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='ubigeo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Distrito'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='unidad_medidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.UnidadMedida'),
        ),
    ]
