# Generated by Django 2.2 on 2020-10-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ruc', models.CharField(help_text=' R.U.C. de Empresa', max_length=11, unique=True)),
                ('razon_social', models.CharField(help_text='Razón Social Empresa', max_length=191)),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre Comercial Empresa', max_length=191, null=True)),
                ('direccion_principal', models.CharField(help_text='Dirección Empresa', max_length=191)),
                ('ubigeo', models.CharField(help_text='Ubigeo Empresa', max_length=191)),
                ('pagina_web', models.CharField(blank=True, help_text='URL / Dirección Web', max_length=191, null=True)),
                ('usuario_sol', models.CharField(blank=True, help_text='Usuario Clave Sol', max_length=50, null=True)),
                ('clave_sol', models.CharField(blank=True, help_text='COntraseña Clave Sol', max_length=50, null=True)),
                ('certificado_pfx', models.BinaryField(blank=True, help_text='Archivo Certificado PFX', null=True)),
                ('fecha_caduca_certificado', models.DateField(blank=True, help_text='Fecha Caduca Certificado', null=True)),
                ('certificado_zip', models.BinaryField(blank=True, help_text='Archivo Certificado Zip', null=True)),
                ('clave_certificado', models.CharField(blank=True, help_text='Contraseña Certificado', max_length=50, null=True)),
                ('texto_encabezado', models.CharField(blank=True, help_text='Texto Encabezado', max_length=191, null=True)),
                ('logo', models.BinaryField(blank=True, help_text='Logo Empresa', null=True)),
                ('imagen_pie_pagina', models.BinaryField(blank=True, help_text='Imagen de Pié de Página', null=True)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
