# Generated by Django 2.2 on 2020-12-11 01:21
from django.db import models,migrations

class EmpresaClase:
    @classmethod
    def cargar_datos(cls,apps,schema_editor):
        db_alias = schema_editor.connection.alias
        Empresa = apps.get_model('emp','Empresa')
        cls.empresa_object, created = Empresa.objects.get_or_create(ruc='10000000001',razon_social="Mi Empresa",direccion_principal='Direccion')
        print(f'\nEmpresa Creada con ID: '+str(cls.empresa_object.id))

class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(EmpresaClase.cargar_datos)
    ]
