# Generated by Django 2.2 on 2020-12-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20201211_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_punto_venta', models.BooleanField(blank=True, help_text='Ocultar Columna Saldo Punto venta', null=True)),
                ('detalle_producto', models.BooleanField(blank=True, help_text='Permitir Detalle Producto', null=True)),
                ('descuento_item_pv', models.BooleanField(blank=True, help_text='Permitir Descuentos por Item en el Punto de Venta', null=True)),
                ('descuento_global', models.BooleanField(blank=True, help_text='Premitir Descuento Global', null=True)),
                ('edicion_precios_pv', models.BooleanField(blank=True, help_text='Permitir la Edición de Precios en los Puntos de Venta', null=True)),
                ('cantidad_precios', models.BooleanField(blank=True, help_text='Permitir 1 o máximo 4 precios de venta', null=True)),
                ('moneda', models.SmallIntegerField(default=0, help_text='Permitir el uso de una(0 o 1) monedas o ambas (2)')),
                ('dias_max_anulacion', models.SmallIntegerField(blank=True, help_text='cantidad de días máximos de boleta emiitida para su anulación', null=True)),
                ('placa_columna', models.BooleanField(blank=True, help_text='Permite la visualualización de la columna placa en el punto de venta', null=True)),
                ('ose_sunat', models.BooleanField(blank=True, help_text='XML se enviará a OSE(0) o SUNAT(1)', null=True)),
                ('direccion_envio_bf', models.CharField(blank=True, help_text='Registramos la dirección que se usará para el envío de los XML de Boletas/Facturas', max_length=191, null=True)),
                ('direccion_envio_ncd', models.CharField(blank=True, help_text='Registramos la dirección que se usará para el envío de los XML de Notas de Crédito/Débito', max_length=191, null=True)),
                ('direccion_envio_gr', models.CharField(blank=True, help_text='Registramos la dirección que usará para el envío de los XML de Guías de Remisión', max_length=191, null=True)),
                ('ubicacion_base_datos', models.SmallIntegerField(default=1, help_text='Indica donde está el servidor de la base de Datos: 0 - local, 1 - Web-Cliente,2 - Web PeruFact')),
                ('cantidad_resumen_boletas', models.SmallIntegerField(default=500, help_text='Cantidad Máxima de Boletas de Resumen')),
                ('envio_xml_boletas', models.SmallIntegerField(default=0, help_text='Envío de XML de Boletas por resumen o individual')),
                ('fecha_inicio_contrato', models.DateField(blank=True, help_text='Fecha de Inicio de Contrato', null=True)),
                ('fecha_renovacion_contrato', models.DateField(blank=True, help_text='Fecha de renovación de Contrato', null=True)),
                ('producto_reemplazo', models.BooleanField(blank=True, help_text='Uso de Productos de Reemplazo', null=True)),
                ('mostrar_codigo_fabricante', models.BooleanField(blank=True, help_text='Mostrar en el Punto de venta el código del fabricante', null=True)),
                ('mostrar_codigo_proveedor', models.BooleanField(blank=True, help_text='Mostrar Código de Proveedor', null=True)),
                ('mostrar_codigo_interno', models.BooleanField(blank=True, help_text='Mostrar Código Interno', null=True)),
                ('mostrar_codigo_sunat', models.BooleanField(blank=True, help_text='Mostrar Código de Sunat', null=True)),
                ('mostrar_codigo_barras', models.BooleanField(blank=True, help_text='Mostrar Código de Barras', null=True)),
                ('ubicacion_exonerado', models.BooleanField(blank=True, help_text='Ubicación de Exonerado del IGV', null=True)),
                ('precio_venta_independiente', models.BooleanField(blank=True, help_text='Precio de Venta Independiente por Caja (0) o Sucursal(1)', null=True)),
                ('vales_salida_efectivo', models.BooleanField(blank=True, help_text='Vales de Salida de Efectivo: (0) No Permite, (1) Permite', null=True)),
                ('vales_producto_factura', models.BooleanField(blank=True, help_text='Vales de Salida de Producto por factura: (0) No Permite, (1) Permite', null=True)),
                ('vales_producto_nofactura', models.BooleanField(blank=True, help_text='Vales de Salida de Producto sin canje por Factura: (0) No Permite, (1) Permite', null=True)),
                ('vales_producto_exclusivo', models.BooleanField(blank=True, help_text='Vales de Salida de Producto Exlusivo para vale: (0) No Permite, (1) Permite', null=True)),
                ('cotizacion', models.BooleanField(blank=True, help_text='Permite Cotización de Productos: (0) No Permite, (1) Permite', null=True)),
                ('empresa', models.ForeignKey(blank=True, help_text='Persona Usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Empresa')),
            ],
            options={
                'verbose_name_plural': 'ConfiguracionEmpresas',
            },
        ),
    ]
