# Generated by Django 2.2 on 2020-11-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20201117_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoempresa',
            name='comentario',
            field=models.CharField(blank=True, help_text='Comentario de Tipo Empresa', max_length=191, null=True),
        ),
    ]
