# Generated by Django 2.2 on 2020-11-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20201117_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Departamento'),
        ),
    ]
