# Generated by Django 2.2 on 2021-01-10 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_auto_20201220_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntoventa',
            name='almacen',
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.Sucursal'),
        ),
    ]
